version: "3.4"
services:
  pgadmin:
    image: dpage/pgadmin4:5.3
    container_name: ampel-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: docker
      PGADMIN_DEFAULT_PASSWORD: docker
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    depends_on:
      - "postgres"
  postgres:
    image: postgres
    container_name: ampel-postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
    volumes:
      - ./data/sql:/var/lib/postgresql/data
  ampel2:
    build: .
    container_name: ampel2
    ports:
      - "7777:7777"
      - "8080:80"
    environment:
      - SIP_INGRESS_HTTP_DEFAULT_DEPLOYMENT_DOMAIN=localhost
      - SIP_INGRESS_HTTP_DEFAULT_CNAMES=

      - SIP_POSTGRES_DB_SERVER=postgres
      - SIP_POSTGRES_DB_PORT=5432
      - SIP_POSTGRES_DB_NAME=postgres
      - SIP_POSTGRES_DB_USER=docker
      - SIP_POSTGRES_DB_PW=docker

    depends_on:
      - postgres
